server:
  id: 1

websocket:
  port: 9999

service:
  host: 0.0.0.0
  port: 18081

discover:
  host: 127.0.0.1
  port: 18088


#spring.main.web-application-type=none
spring:
  main:
    web-application-type: none
  profiles:
    active: dev

logging:
  level:
    root: info
    com:
      seeu: debug
  file: log/access_${server.id}.log
