server:
  id: 1
  wss:
    open: false
    certificate: legame_dev.jks
    password: legame123

websocket:
  port: 9999

#spring.main.web-application-type=none
spring:
  main:
    web-application-type: none

logging:
  level:
    root: info
    com:
      seeu: debug

