// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: discover.proto

package com.seeu.proto;

public final class Discover {
  private Discover() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface registerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.seeu.proto.register)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
     * @return The enum numeric value on the wire for svrType.
     */
    int getSvrTypeValue();
    /**
     * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
     * @return The svrType.
     */
    com.seeu.framework.rpc.RpcMsg.ServerType getSvrType();

    /**
     * <code>int32 svrId = 2;</code>
     * @return The svrId.
     */
    int getSvrId();

    /**
     * <code>string host = 3;</code>
     * @return The host.
     */
    java.lang.String getHost();
    /**
     * <code>string host = 3;</code>
     * @return The bytes for host.
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>int32 port = 4;</code>
     * @return The port.
     */
    int getPort();
  }
  /**
   * Protobuf type {@code com.seeu.proto.register}
   */
  public  static final class register extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.seeu.proto.register)
      registerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use register.newBuilder() to construct.
    private register(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private register() {
      svrType_ = 0;
      host_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new register();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private register(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              svrType_ = rawValue;
              break;
            }
            case 16: {

              svrId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 32: {

              port_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seeu.proto.Discover.internal_static_com_seeu_proto_register_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seeu.proto.Discover.internal_static_com_seeu_proto_register_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seeu.proto.Discover.register.class, com.seeu.proto.Discover.register.Builder.class);
    }

    public static final int SVRTYPE_FIELD_NUMBER = 1;
    private int svrType_;
    /**
     * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
     * @return The enum numeric value on the wire for svrType.
     */
    public int getSvrTypeValue() {
      return svrType_;
    }
    /**
     * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
     * @return The svrType.
     */
    public com.seeu.framework.rpc.RpcMsg.ServerType getSvrType() {
      @SuppressWarnings("deprecation")
      com.seeu.framework.rpc.RpcMsg.ServerType result = com.seeu.framework.rpc.RpcMsg.ServerType.valueOf(svrType_);
      return result == null ? com.seeu.framework.rpc.RpcMsg.ServerType.UNRECOGNIZED : result;
    }

    public static final int SVRID_FIELD_NUMBER = 2;
    private int svrId_;
    /**
     * <code>int32 svrId = 2;</code>
     * @return The svrId.
     */
    public int getSvrId() {
      return svrId_;
    }

    public static final int HOST_FIELD_NUMBER = 3;
    private volatile java.lang.Object host_;
    /**
     * <code>string host = 3;</code>
     * @return The host.
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>string host = 3;</code>
     * @return The bytes for host.
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 4;
    private int port_;
    /**
     * <code>int32 port = 4;</code>
     * @return The port.
     */
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (svrType_ != com.seeu.framework.rpc.RpcMsg.ServerType.UNKNOWN.getNumber()) {
        output.writeEnum(1, svrType_);
      }
      if (svrId_ != 0) {
        output.writeInt32(2, svrId_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, host_);
      }
      if (port_ != 0) {
        output.writeInt32(4, port_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (svrType_ != com.seeu.framework.rpc.RpcMsg.ServerType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, svrType_);
      }
      if (svrId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, svrId_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, host_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.seeu.proto.Discover.register)) {
        return super.equals(obj);
      }
      com.seeu.proto.Discover.register other = (com.seeu.proto.Discover.register) obj;

      if (svrType_ != other.svrType_) return false;
      if (getSvrId()
          != other.getSvrId()) return false;
      if (!getHost()
          .equals(other.getHost())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SVRTYPE_FIELD_NUMBER;
      hash = (53 * hash) + svrType_;
      hash = (37 * hash) + SVRID_FIELD_NUMBER;
      hash = (53 * hash) + getSvrId();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.seeu.proto.Discover.register parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.proto.Discover.register parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.proto.Discover.register parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.proto.Discover.register parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.proto.Discover.register parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.proto.Discover.register parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.proto.Discover.register parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeu.proto.Discover.register parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeu.proto.Discover.register parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.seeu.proto.Discover.register parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeu.proto.Discover.register parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeu.proto.Discover.register parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.seeu.proto.Discover.register prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.seeu.proto.register}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.seeu.proto.register)
        com.seeu.proto.Discover.registerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.seeu.proto.Discover.internal_static_com_seeu_proto_register_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.seeu.proto.Discover.internal_static_com_seeu_proto_register_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.seeu.proto.Discover.register.class, com.seeu.proto.Discover.register.Builder.class);
      }

      // Construct using com.seeu.proto.Discover.register.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        svrType_ = 0;

        svrId_ = 0;

        host_ = "";

        port_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.seeu.proto.Discover.internal_static_com_seeu_proto_register_descriptor;
      }

      @java.lang.Override
      public com.seeu.proto.Discover.register getDefaultInstanceForType() {
        return com.seeu.proto.Discover.register.getDefaultInstance();
      }

      @java.lang.Override
      public com.seeu.proto.Discover.register build() {
        com.seeu.proto.Discover.register result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.seeu.proto.Discover.register buildPartial() {
        com.seeu.proto.Discover.register result = new com.seeu.proto.Discover.register(this);
        result.svrType_ = svrType_;
        result.svrId_ = svrId_;
        result.host_ = host_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.seeu.proto.Discover.register) {
          return mergeFrom((com.seeu.proto.Discover.register)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.seeu.proto.Discover.register other) {
        if (other == com.seeu.proto.Discover.register.getDefaultInstance()) return this;
        if (other.svrType_ != 0) {
          setSvrTypeValue(other.getSvrTypeValue());
        }
        if (other.getSvrId() != 0) {
          setSvrId(other.getSvrId());
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.seeu.proto.Discover.register parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.seeu.proto.Discover.register) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int svrType_ = 0;
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @return The enum numeric value on the wire for svrType.
       */
      public int getSvrTypeValue() {
        return svrType_;
      }
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @param value The enum numeric value on the wire for svrType to set.
       * @return This builder for chaining.
       */
      public Builder setSvrTypeValue(int value) {
        svrType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @return The svrType.
       */
      public com.seeu.framework.rpc.RpcMsg.ServerType getSvrType() {
        @SuppressWarnings("deprecation")
        com.seeu.framework.rpc.RpcMsg.ServerType result = com.seeu.framework.rpc.RpcMsg.ServerType.valueOf(svrType_);
        return result == null ? com.seeu.framework.rpc.RpcMsg.ServerType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @param value The svrType to set.
       * @return This builder for chaining.
       */
      public Builder setSvrType(com.seeu.framework.rpc.RpcMsg.ServerType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        svrType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSvrType() {
        
        svrType_ = 0;
        onChanged();
        return this;
      }

      private int svrId_ ;
      /**
       * <code>int32 svrId = 2;</code>
       * @return The svrId.
       */
      public int getSvrId() {
        return svrId_;
      }
      /**
       * <code>int32 svrId = 2;</code>
       * @param value The svrId to set.
       * @return This builder for chaining.
       */
      public Builder setSvrId(int value) {
        
        svrId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 svrId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSvrId() {
        
        svrId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <code>string host = 3;</code>
       * @return The host.
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string host = 3;</code>
       * @return The bytes for host.
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string host = 3;</code>
       * @param value The host to set.
       * @return This builder for chaining.
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string host = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>string host = 3;</code>
       * @param value The bytes for host to set.
       * @return This builder for chaining.
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 4;</code>
       * @return The port.
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 4;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.seeu.proto.register)
    }

    // @@protoc_insertion_point(class_scope:com.seeu.proto.register)
    private static final com.seeu.proto.Discover.register DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.seeu.proto.Discover.register();
    }

    public static com.seeu.proto.Discover.register getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<register>
        PARSER = new com.google.protobuf.AbstractParser<register>() {
      @java.lang.Override
      public register parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new register(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<register> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<register> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.seeu.proto.Discover.register getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface unregisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.seeu.proto.unregister)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
     * @return The enum numeric value on the wire for svrType.
     */
    int getSvrTypeValue();
    /**
     * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
     * @return The svrType.
     */
    com.seeu.framework.rpc.RpcMsg.ServerType getSvrType();

    /**
     * <code>int32 svrId = 2;</code>
     * @return The svrId.
     */
    int getSvrId();
  }
  /**
   * Protobuf type {@code com.seeu.proto.unregister}
   */
  public  static final class unregister extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.seeu.proto.unregister)
      unregisterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use unregister.newBuilder() to construct.
    private unregister(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private unregister() {
      svrType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new unregister();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private unregister(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              svrType_ = rawValue;
              break;
            }
            case 16: {

              svrId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seeu.proto.Discover.internal_static_com_seeu_proto_unregister_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seeu.proto.Discover.internal_static_com_seeu_proto_unregister_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seeu.proto.Discover.unregister.class, com.seeu.proto.Discover.unregister.Builder.class);
    }

    public static final int SVRTYPE_FIELD_NUMBER = 1;
    private int svrType_;
    /**
     * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
     * @return The enum numeric value on the wire for svrType.
     */
    public int getSvrTypeValue() {
      return svrType_;
    }
    /**
     * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
     * @return The svrType.
     */
    public com.seeu.framework.rpc.RpcMsg.ServerType getSvrType() {
      @SuppressWarnings("deprecation")
      com.seeu.framework.rpc.RpcMsg.ServerType result = com.seeu.framework.rpc.RpcMsg.ServerType.valueOf(svrType_);
      return result == null ? com.seeu.framework.rpc.RpcMsg.ServerType.UNRECOGNIZED : result;
    }

    public static final int SVRID_FIELD_NUMBER = 2;
    private int svrId_;
    /**
     * <code>int32 svrId = 2;</code>
     * @return The svrId.
     */
    public int getSvrId() {
      return svrId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (svrType_ != com.seeu.framework.rpc.RpcMsg.ServerType.UNKNOWN.getNumber()) {
        output.writeEnum(1, svrType_);
      }
      if (svrId_ != 0) {
        output.writeInt32(2, svrId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (svrType_ != com.seeu.framework.rpc.RpcMsg.ServerType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, svrType_);
      }
      if (svrId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, svrId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.seeu.proto.Discover.unregister)) {
        return super.equals(obj);
      }
      com.seeu.proto.Discover.unregister other = (com.seeu.proto.Discover.unregister) obj;

      if (svrType_ != other.svrType_) return false;
      if (getSvrId()
          != other.getSvrId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SVRTYPE_FIELD_NUMBER;
      hash = (53 * hash) + svrType_;
      hash = (37 * hash) + SVRID_FIELD_NUMBER;
      hash = (53 * hash) + getSvrId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.seeu.proto.Discover.unregister parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.proto.Discover.unregister parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.proto.Discover.unregister parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.proto.Discover.unregister parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.proto.Discover.unregister parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.proto.Discover.unregister parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.proto.Discover.unregister parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeu.proto.Discover.unregister parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeu.proto.Discover.unregister parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.seeu.proto.Discover.unregister parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeu.proto.Discover.unregister parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeu.proto.Discover.unregister parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.seeu.proto.Discover.unregister prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.seeu.proto.unregister}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.seeu.proto.unregister)
        com.seeu.proto.Discover.unregisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.seeu.proto.Discover.internal_static_com_seeu_proto_unregister_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.seeu.proto.Discover.internal_static_com_seeu_proto_unregister_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.seeu.proto.Discover.unregister.class, com.seeu.proto.Discover.unregister.Builder.class);
      }

      // Construct using com.seeu.proto.Discover.unregister.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        svrType_ = 0;

        svrId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.seeu.proto.Discover.internal_static_com_seeu_proto_unregister_descriptor;
      }

      @java.lang.Override
      public com.seeu.proto.Discover.unregister getDefaultInstanceForType() {
        return com.seeu.proto.Discover.unregister.getDefaultInstance();
      }

      @java.lang.Override
      public com.seeu.proto.Discover.unregister build() {
        com.seeu.proto.Discover.unregister result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.seeu.proto.Discover.unregister buildPartial() {
        com.seeu.proto.Discover.unregister result = new com.seeu.proto.Discover.unregister(this);
        result.svrType_ = svrType_;
        result.svrId_ = svrId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.seeu.proto.Discover.unregister) {
          return mergeFrom((com.seeu.proto.Discover.unregister)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.seeu.proto.Discover.unregister other) {
        if (other == com.seeu.proto.Discover.unregister.getDefaultInstance()) return this;
        if (other.svrType_ != 0) {
          setSvrTypeValue(other.getSvrTypeValue());
        }
        if (other.getSvrId() != 0) {
          setSvrId(other.getSvrId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.seeu.proto.Discover.unregister parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.seeu.proto.Discover.unregister) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int svrType_ = 0;
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @return The enum numeric value on the wire for svrType.
       */
      public int getSvrTypeValue() {
        return svrType_;
      }
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @param value The enum numeric value on the wire for svrType to set.
       * @return This builder for chaining.
       */
      public Builder setSvrTypeValue(int value) {
        svrType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @return The svrType.
       */
      public com.seeu.framework.rpc.RpcMsg.ServerType getSvrType() {
        @SuppressWarnings("deprecation")
        com.seeu.framework.rpc.RpcMsg.ServerType result = com.seeu.framework.rpc.RpcMsg.ServerType.valueOf(svrType_);
        return result == null ? com.seeu.framework.rpc.RpcMsg.ServerType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @param value The svrType to set.
       * @return This builder for chaining.
       */
      public Builder setSvrType(com.seeu.framework.rpc.RpcMsg.ServerType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        svrType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSvrType() {
        
        svrType_ = 0;
        onChanged();
        return this;
      }

      private int svrId_ ;
      /**
       * <code>int32 svrId = 2;</code>
       * @return The svrId.
       */
      public int getSvrId() {
        return svrId_;
      }
      /**
       * <code>int32 svrId = 2;</code>
       * @param value The svrId to set.
       * @return This builder for chaining.
       */
      public Builder setSvrId(int value) {
        
        svrId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 svrId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSvrId() {
        
        svrId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.seeu.proto.unregister)
    }

    // @@protoc_insertion_point(class_scope:com.seeu.proto.unregister)
    private static final com.seeu.proto.Discover.unregister DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.seeu.proto.Discover.unregister();
    }

    public static com.seeu.proto.Discover.unregister getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<unregister>
        PARSER = new com.google.protobuf.AbstractParser<unregister>() {
      @java.lang.Override
      public unregister parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new unregister(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<unregister> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<unregister> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.seeu.proto.Discover.unregister getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface getServiceInfoReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.seeu.proto.getServiceInfoReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *服务类型
     * </pre>
     *
     * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
     * @return The enum numeric value on the wire for svrType.
     */
    int getSvrTypeValue();
    /**
     * <pre>
     *服务类型
     * </pre>
     *
     * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
     * @return The svrType.
     */
    com.seeu.framework.rpc.RpcMsg.ServerType getSvrType();

    /**
     * <pre>
     *服务id
     * </pre>
     *
     * <code>int32 svrId = 2;</code>
     * @return The svrId.
     */
    int getSvrId();
  }
  /**
   * <pre>
   *向服务发现服务获取指定服务信息
   * </pre>
   *
   * Protobuf type {@code com.seeu.proto.getServiceInfoReq}
   */
  public  static final class getServiceInfoReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.seeu.proto.getServiceInfoReq)
      getServiceInfoReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use getServiceInfoReq.newBuilder() to construct.
    private getServiceInfoReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private getServiceInfoReq() {
      svrType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new getServiceInfoReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private getServiceInfoReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              svrType_ = rawValue;
              break;
            }
            case 16: {

              svrId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seeu.proto.Discover.internal_static_com_seeu_proto_getServiceInfoReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seeu.proto.Discover.internal_static_com_seeu_proto_getServiceInfoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seeu.proto.Discover.getServiceInfoReq.class, com.seeu.proto.Discover.getServiceInfoReq.Builder.class);
    }

    public static final int SVRTYPE_FIELD_NUMBER = 1;
    private int svrType_;
    /**
     * <pre>
     *服务类型
     * </pre>
     *
     * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
     * @return The enum numeric value on the wire for svrType.
     */
    public int getSvrTypeValue() {
      return svrType_;
    }
    /**
     * <pre>
     *服务类型
     * </pre>
     *
     * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
     * @return The svrType.
     */
    public com.seeu.framework.rpc.RpcMsg.ServerType getSvrType() {
      @SuppressWarnings("deprecation")
      com.seeu.framework.rpc.RpcMsg.ServerType result = com.seeu.framework.rpc.RpcMsg.ServerType.valueOf(svrType_);
      return result == null ? com.seeu.framework.rpc.RpcMsg.ServerType.UNRECOGNIZED : result;
    }

    public static final int SVRID_FIELD_NUMBER = 2;
    private int svrId_;
    /**
     * <pre>
     *服务id
     * </pre>
     *
     * <code>int32 svrId = 2;</code>
     * @return The svrId.
     */
    public int getSvrId() {
      return svrId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (svrType_ != com.seeu.framework.rpc.RpcMsg.ServerType.UNKNOWN.getNumber()) {
        output.writeEnum(1, svrType_);
      }
      if (svrId_ != 0) {
        output.writeInt32(2, svrId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (svrType_ != com.seeu.framework.rpc.RpcMsg.ServerType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, svrType_);
      }
      if (svrId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, svrId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.seeu.proto.Discover.getServiceInfoReq)) {
        return super.equals(obj);
      }
      com.seeu.proto.Discover.getServiceInfoReq other = (com.seeu.proto.Discover.getServiceInfoReq) obj;

      if (svrType_ != other.svrType_) return false;
      if (getSvrId()
          != other.getSvrId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SVRTYPE_FIELD_NUMBER;
      hash = (53 * hash) + svrType_;
      hash = (37 * hash) + SVRID_FIELD_NUMBER;
      hash = (53 * hash) + getSvrId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.seeu.proto.Discover.getServiceInfoReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.proto.Discover.getServiceInfoReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.proto.Discover.getServiceInfoReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.proto.Discover.getServiceInfoReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.proto.Discover.getServiceInfoReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.proto.Discover.getServiceInfoReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.proto.Discover.getServiceInfoReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeu.proto.Discover.getServiceInfoReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeu.proto.Discover.getServiceInfoReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.seeu.proto.Discover.getServiceInfoReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeu.proto.Discover.getServiceInfoReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeu.proto.Discover.getServiceInfoReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.seeu.proto.Discover.getServiceInfoReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *向服务发现服务获取指定服务信息
     * </pre>
     *
     * Protobuf type {@code com.seeu.proto.getServiceInfoReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.seeu.proto.getServiceInfoReq)
        com.seeu.proto.Discover.getServiceInfoReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.seeu.proto.Discover.internal_static_com_seeu_proto_getServiceInfoReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.seeu.proto.Discover.internal_static_com_seeu_proto_getServiceInfoReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.seeu.proto.Discover.getServiceInfoReq.class, com.seeu.proto.Discover.getServiceInfoReq.Builder.class);
      }

      // Construct using com.seeu.proto.Discover.getServiceInfoReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        svrType_ = 0;

        svrId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.seeu.proto.Discover.internal_static_com_seeu_proto_getServiceInfoReq_descriptor;
      }

      @java.lang.Override
      public com.seeu.proto.Discover.getServiceInfoReq getDefaultInstanceForType() {
        return com.seeu.proto.Discover.getServiceInfoReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.seeu.proto.Discover.getServiceInfoReq build() {
        com.seeu.proto.Discover.getServiceInfoReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.seeu.proto.Discover.getServiceInfoReq buildPartial() {
        com.seeu.proto.Discover.getServiceInfoReq result = new com.seeu.proto.Discover.getServiceInfoReq(this);
        result.svrType_ = svrType_;
        result.svrId_ = svrId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.seeu.proto.Discover.getServiceInfoReq) {
          return mergeFrom((com.seeu.proto.Discover.getServiceInfoReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.seeu.proto.Discover.getServiceInfoReq other) {
        if (other == com.seeu.proto.Discover.getServiceInfoReq.getDefaultInstance()) return this;
        if (other.svrType_ != 0) {
          setSvrTypeValue(other.getSvrTypeValue());
        }
        if (other.getSvrId() != 0) {
          setSvrId(other.getSvrId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.seeu.proto.Discover.getServiceInfoReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.seeu.proto.Discover.getServiceInfoReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int svrType_ = 0;
      /**
       * <pre>
       *服务类型
       * </pre>
       *
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @return The enum numeric value on the wire for svrType.
       */
      public int getSvrTypeValue() {
        return svrType_;
      }
      /**
       * <pre>
       *服务类型
       * </pre>
       *
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @param value The enum numeric value on the wire for svrType to set.
       * @return This builder for chaining.
       */
      public Builder setSvrTypeValue(int value) {
        svrType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务类型
       * </pre>
       *
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @return The svrType.
       */
      public com.seeu.framework.rpc.RpcMsg.ServerType getSvrType() {
        @SuppressWarnings("deprecation")
        com.seeu.framework.rpc.RpcMsg.ServerType result = com.seeu.framework.rpc.RpcMsg.ServerType.valueOf(svrType_);
        return result == null ? com.seeu.framework.rpc.RpcMsg.ServerType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *服务类型
       * </pre>
       *
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @param value The svrType to set.
       * @return This builder for chaining.
       */
      public Builder setSvrType(com.seeu.framework.rpc.RpcMsg.ServerType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        svrType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务类型
       * </pre>
       *
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSvrType() {
        
        svrType_ = 0;
        onChanged();
        return this;
      }

      private int svrId_ ;
      /**
       * <pre>
       *服务id
       * </pre>
       *
       * <code>int32 svrId = 2;</code>
       * @return The svrId.
       */
      public int getSvrId() {
        return svrId_;
      }
      /**
       * <pre>
       *服务id
       * </pre>
       *
       * <code>int32 svrId = 2;</code>
       * @param value The svrId to set.
       * @return This builder for chaining.
       */
      public Builder setSvrId(int value) {
        
        svrId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务id
       * </pre>
       *
       * <code>int32 svrId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSvrId() {
        
        svrId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.seeu.proto.getServiceInfoReq)
    }

    // @@protoc_insertion_point(class_scope:com.seeu.proto.getServiceInfoReq)
    private static final com.seeu.proto.Discover.getServiceInfoReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.seeu.proto.Discover.getServiceInfoReq();
    }

    public static com.seeu.proto.Discover.getServiceInfoReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<getServiceInfoReq>
        PARSER = new com.google.protobuf.AbstractParser<getServiceInfoReq>() {
      @java.lang.Override
      public getServiceInfoReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getServiceInfoReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<getServiceInfoReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<getServiceInfoReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.seeu.proto.Discover.getServiceInfoReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface getServiceInfoRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.seeu.proto.getServiceInfoResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *服务类型，若该服务类型不存在，则会返回UNKNOWN
     * </pre>
     *
     * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
     * @return The enum numeric value on the wire for svrType.
     */
    int getSvrTypeValue();
    /**
     * <pre>
     *服务类型，若该服务类型不存在，则会返回UNKNOWN
     * </pre>
     *
     * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
     * @return The svrType.
     */
    com.seeu.framework.rpc.RpcMsg.ServerType getSvrType();

    /**
     * <pre>
     *服务id,若请求的服务不存在，则会随机分配一个同类服务
     * </pre>
     *
     * <code>int32 svrId = 2;</code>
     * @return The svrId.
     */
    int getSvrId();

    /**
     * <code>string host = 3;</code>
     * @return The host.
     */
    java.lang.String getHost();
    /**
     * <code>string host = 3;</code>
     * @return The bytes for host.
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>int32 port = 4;</code>
     * @return The port.
     */
    int getPort();
  }
  /**
   * <pre>
   *向服务发现服务获取指定服务信息
   * </pre>
   *
   * Protobuf type {@code com.seeu.proto.getServiceInfoResp}
   */
  public  static final class getServiceInfoResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.seeu.proto.getServiceInfoResp)
      getServiceInfoRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use getServiceInfoResp.newBuilder() to construct.
    private getServiceInfoResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private getServiceInfoResp() {
      svrType_ = 0;
      host_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new getServiceInfoResp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private getServiceInfoResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              svrType_ = rawValue;
              break;
            }
            case 16: {

              svrId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 32: {

              port_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seeu.proto.Discover.internal_static_com_seeu_proto_getServiceInfoResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seeu.proto.Discover.internal_static_com_seeu_proto_getServiceInfoResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seeu.proto.Discover.getServiceInfoResp.class, com.seeu.proto.Discover.getServiceInfoResp.Builder.class);
    }

    public static final int SVRTYPE_FIELD_NUMBER = 1;
    private int svrType_;
    /**
     * <pre>
     *服务类型，若该服务类型不存在，则会返回UNKNOWN
     * </pre>
     *
     * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
     * @return The enum numeric value on the wire for svrType.
     */
    public int getSvrTypeValue() {
      return svrType_;
    }
    /**
     * <pre>
     *服务类型，若该服务类型不存在，则会返回UNKNOWN
     * </pre>
     *
     * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
     * @return The svrType.
     */
    public com.seeu.framework.rpc.RpcMsg.ServerType getSvrType() {
      @SuppressWarnings("deprecation")
      com.seeu.framework.rpc.RpcMsg.ServerType result = com.seeu.framework.rpc.RpcMsg.ServerType.valueOf(svrType_);
      return result == null ? com.seeu.framework.rpc.RpcMsg.ServerType.UNRECOGNIZED : result;
    }

    public static final int SVRID_FIELD_NUMBER = 2;
    private int svrId_;
    /**
     * <pre>
     *服务id,若请求的服务不存在，则会随机分配一个同类服务
     * </pre>
     *
     * <code>int32 svrId = 2;</code>
     * @return The svrId.
     */
    public int getSvrId() {
      return svrId_;
    }

    public static final int HOST_FIELD_NUMBER = 3;
    private volatile java.lang.Object host_;
    /**
     * <code>string host = 3;</code>
     * @return The host.
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>string host = 3;</code>
     * @return The bytes for host.
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 4;
    private int port_;
    /**
     * <code>int32 port = 4;</code>
     * @return The port.
     */
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (svrType_ != com.seeu.framework.rpc.RpcMsg.ServerType.UNKNOWN.getNumber()) {
        output.writeEnum(1, svrType_);
      }
      if (svrId_ != 0) {
        output.writeInt32(2, svrId_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, host_);
      }
      if (port_ != 0) {
        output.writeInt32(4, port_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (svrType_ != com.seeu.framework.rpc.RpcMsg.ServerType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, svrType_);
      }
      if (svrId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, svrId_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, host_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.seeu.proto.Discover.getServiceInfoResp)) {
        return super.equals(obj);
      }
      com.seeu.proto.Discover.getServiceInfoResp other = (com.seeu.proto.Discover.getServiceInfoResp) obj;

      if (svrType_ != other.svrType_) return false;
      if (getSvrId()
          != other.getSvrId()) return false;
      if (!getHost()
          .equals(other.getHost())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SVRTYPE_FIELD_NUMBER;
      hash = (53 * hash) + svrType_;
      hash = (37 * hash) + SVRID_FIELD_NUMBER;
      hash = (53 * hash) + getSvrId();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.seeu.proto.Discover.getServiceInfoResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.proto.Discover.getServiceInfoResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.proto.Discover.getServiceInfoResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.proto.Discover.getServiceInfoResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.proto.Discover.getServiceInfoResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.proto.Discover.getServiceInfoResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.proto.Discover.getServiceInfoResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeu.proto.Discover.getServiceInfoResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeu.proto.Discover.getServiceInfoResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.seeu.proto.Discover.getServiceInfoResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeu.proto.Discover.getServiceInfoResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeu.proto.Discover.getServiceInfoResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.seeu.proto.Discover.getServiceInfoResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *向服务发现服务获取指定服务信息
     * </pre>
     *
     * Protobuf type {@code com.seeu.proto.getServiceInfoResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.seeu.proto.getServiceInfoResp)
        com.seeu.proto.Discover.getServiceInfoRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.seeu.proto.Discover.internal_static_com_seeu_proto_getServiceInfoResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.seeu.proto.Discover.internal_static_com_seeu_proto_getServiceInfoResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.seeu.proto.Discover.getServiceInfoResp.class, com.seeu.proto.Discover.getServiceInfoResp.Builder.class);
      }

      // Construct using com.seeu.proto.Discover.getServiceInfoResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        svrType_ = 0;

        svrId_ = 0;

        host_ = "";

        port_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.seeu.proto.Discover.internal_static_com_seeu_proto_getServiceInfoResp_descriptor;
      }

      @java.lang.Override
      public com.seeu.proto.Discover.getServiceInfoResp getDefaultInstanceForType() {
        return com.seeu.proto.Discover.getServiceInfoResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.seeu.proto.Discover.getServiceInfoResp build() {
        com.seeu.proto.Discover.getServiceInfoResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.seeu.proto.Discover.getServiceInfoResp buildPartial() {
        com.seeu.proto.Discover.getServiceInfoResp result = new com.seeu.proto.Discover.getServiceInfoResp(this);
        result.svrType_ = svrType_;
        result.svrId_ = svrId_;
        result.host_ = host_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.seeu.proto.Discover.getServiceInfoResp) {
          return mergeFrom((com.seeu.proto.Discover.getServiceInfoResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.seeu.proto.Discover.getServiceInfoResp other) {
        if (other == com.seeu.proto.Discover.getServiceInfoResp.getDefaultInstance()) return this;
        if (other.svrType_ != 0) {
          setSvrTypeValue(other.getSvrTypeValue());
        }
        if (other.getSvrId() != 0) {
          setSvrId(other.getSvrId());
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.seeu.proto.Discover.getServiceInfoResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.seeu.proto.Discover.getServiceInfoResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int svrType_ = 0;
      /**
       * <pre>
       *服务类型，若该服务类型不存在，则会返回UNKNOWN
       * </pre>
       *
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @return The enum numeric value on the wire for svrType.
       */
      public int getSvrTypeValue() {
        return svrType_;
      }
      /**
       * <pre>
       *服务类型，若该服务类型不存在，则会返回UNKNOWN
       * </pre>
       *
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @param value The enum numeric value on the wire for svrType to set.
       * @return This builder for chaining.
       */
      public Builder setSvrTypeValue(int value) {
        svrType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务类型，若该服务类型不存在，则会返回UNKNOWN
       * </pre>
       *
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @return The svrType.
       */
      public com.seeu.framework.rpc.RpcMsg.ServerType getSvrType() {
        @SuppressWarnings("deprecation")
        com.seeu.framework.rpc.RpcMsg.ServerType result = com.seeu.framework.rpc.RpcMsg.ServerType.valueOf(svrType_);
        return result == null ? com.seeu.framework.rpc.RpcMsg.ServerType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *服务类型，若该服务类型不存在，则会返回UNKNOWN
       * </pre>
       *
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @param value The svrType to set.
       * @return This builder for chaining.
       */
      public Builder setSvrType(com.seeu.framework.rpc.RpcMsg.ServerType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        svrType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务类型，若该服务类型不存在，则会返回UNKNOWN
       * </pre>
       *
       * <code>.com.seeu.framework.rpc.ServerType svrType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSvrType() {
        
        svrType_ = 0;
        onChanged();
        return this;
      }

      private int svrId_ ;
      /**
       * <pre>
       *服务id,若请求的服务不存在，则会随机分配一个同类服务
       * </pre>
       *
       * <code>int32 svrId = 2;</code>
       * @return The svrId.
       */
      public int getSvrId() {
        return svrId_;
      }
      /**
       * <pre>
       *服务id,若请求的服务不存在，则会随机分配一个同类服务
       * </pre>
       *
       * <code>int32 svrId = 2;</code>
       * @param value The svrId to set.
       * @return This builder for chaining.
       */
      public Builder setSvrId(int value) {
        
        svrId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务id,若请求的服务不存在，则会随机分配一个同类服务
       * </pre>
       *
       * <code>int32 svrId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSvrId() {
        
        svrId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <code>string host = 3;</code>
       * @return The host.
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string host = 3;</code>
       * @return The bytes for host.
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string host = 3;</code>
       * @param value The host to set.
       * @return This builder for chaining.
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string host = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>string host = 3;</code>
       * @param value The bytes for host to set.
       * @return This builder for chaining.
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 4;</code>
       * @return The port.
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 4;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.seeu.proto.getServiceInfoResp)
    }

    // @@protoc_insertion_point(class_scope:com.seeu.proto.getServiceInfoResp)
    private static final com.seeu.proto.Discover.getServiceInfoResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.seeu.proto.Discover.getServiceInfoResp();
    }

    public static com.seeu.proto.Discover.getServiceInfoResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<getServiceInfoResp>
        PARSER = new com.google.protobuf.AbstractParser<getServiceInfoResp>() {
      @java.lang.Override
      public getServiceInfoResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getServiceInfoResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<getServiceInfoResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<getServiceInfoResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.seeu.proto.Discover.getServiceInfoResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seeu_proto_register_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seeu_proto_register_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seeu_proto_unregister_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seeu_proto_unregister_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seeu_proto_getServiceInfoReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seeu_proto_getServiceInfoReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seeu_proto_getServiceInfoResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seeu_proto_getServiceInfoResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016discover.proto\022\016com.seeu.proto\032\014rpcMsg" +
      ".proto\"j\n\010register\0223\n\007svrType\030\001 \001(\0162\".co" +
      "m.seeu.framework.rpc.ServerType\022\r\n\005svrId" +
      "\030\002 \001(\005\022\014\n\004host\030\003 \001(\t\022\014\n\004port\030\004 \001(\005\"P\n\nun" +
      "register\0223\n\007svrType\030\001 \001(\0162\".com.seeu.fra" +
      "mework.rpc.ServerType\022\r\n\005svrId\030\002 \001(\005\"W\n\021" +
      "getServiceInfoReq\0223\n\007svrType\030\001 \001(\0162\".com" +
      ".seeu.framework.rpc.ServerType\022\r\n\005svrId\030" +
      "\002 \001(\005\"t\n\022getServiceInfoResp\0223\n\007svrType\030\001" +
      " \001(\0162\".com.seeu.framework.rpc.ServerType" +
      "\022\r\n\005svrId\030\002 \001(\005\022\014\n\004host\030\003 \001(\t\022\014\n\004port\030\004 " +
      "\001(\005B\032\n\016com.seeu.protoB\010Discoverb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.seeu.framework.rpc.RpcMsg.getDescriptor(),
        });
    internal_static_com_seeu_proto_register_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_seeu_proto_register_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seeu_proto_register_descriptor,
        new java.lang.String[] { "SvrType", "SvrId", "Host", "Port", });
    internal_static_com_seeu_proto_unregister_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_seeu_proto_unregister_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seeu_proto_unregister_descriptor,
        new java.lang.String[] { "SvrType", "SvrId", });
    internal_static_com_seeu_proto_getServiceInfoReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_seeu_proto_getServiceInfoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seeu_proto_getServiceInfoReq_descriptor,
        new java.lang.String[] { "SvrType", "SvrId", });
    internal_static_com_seeu_proto_getServiceInfoResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_seeu_proto_getServiceInfoResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seeu_proto_getServiceInfoResp_descriptor,
        new java.lang.String[] { "SvrType", "SvrId", "Host", "Port", });
    com.seeu.framework.rpc.RpcMsg.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
