server:
  id: 1
  port: 18088

#spring.main.web-application-type=none
spring:
  main:
    web-application-type: none
  profiles:
    active: dev

logging:
  level:
    root: debug
  file: log/discover_${server.id}.log
