// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcMsg.proto

package com.seeu.framework.rpc;

public final class RpcMsg {
  private RpcMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.seeu.framework.rpc.ServerType}
   */
  public enum ServerType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>DISCOVER = 1;</code>
     */
    DISCOVER(1),
    /**
     * <code>ACCESS = 2;</code>
     */
    ACCESS(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>DISCOVER = 1;</code>
     */
    public static final int DISCOVER_VALUE = 1;
    /**
     * <code>ACCESS = 2;</code>
     */
    public static final int ACCESS_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ServerType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ServerType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return DISCOVER;
        case 2: return ACCESS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ServerType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ServerType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ServerType>() {
            public ServerType findValueByNumber(int number) {
              return ServerType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.seeu.framework.rpc.RpcMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final ServerType[] VALUES = values();

    public static ServerType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ServerType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.seeu.framework.rpc.ServerType)
  }

  public interface requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.seeu.framework.rpc.request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息唯一标识，与对应的response一致。
     * </pre>
     *
     * <code>int32 msgSeq = 1;</code>
     * @return The msgSeq.
     */
    int getMsgSeq();

    /**
     * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
     * @return The enum numeric value on the wire for svrType.
     */
    int getSvrTypeValue();
    /**
     * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
     * @return The svrType.
     */
    com.seeu.framework.rpc.RpcMsg.ServerType getSvrType();

    /**
     * <code>int32 svrId = 3;</code>
     * @return The svrId.
     */
    int getSvrId();

    /**
     * <pre>
     *具体消息命令字定义，比如：user.login
     * </pre>
     *
     * <code>string method = 4;</code>
     * @return The method.
     */
    java.lang.String getMethod();
    /**
     * <pre>
     *具体消息命令字定义，比如：user.login
     * </pre>
     *
     * <code>string method = 4;</code>
     * @return The bytes for method.
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <pre>
     *是否需要等待响应
     * </pre>
     *
     * <code>bool needResponse = 5;</code>
     * @return The needResponse.
     */
    boolean getNeedResponse();

    /**
     * <pre>
     *消息内容。
     * </pre>
     *
     * <code>bytes content = 6;</code>
     * @return The content.
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code com.seeu.framework.rpc.request}
   */
  public  static final class request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.seeu.framework.rpc.request)
      requestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use request.newBuilder() to construct.
    private request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private request() {
      svrType_ = 0;
      method_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgSeq_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              svrType_ = rawValue;
              break;
            }
            case 24: {

              svrId_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            case 40: {

              needResponse_ = input.readBool();
              break;
            }
            case 50: {

              content_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seeu.framework.rpc.RpcMsg.request.class, com.seeu.framework.rpc.RpcMsg.request.Builder.class);
    }

    public static final int MSGSEQ_FIELD_NUMBER = 1;
    private int msgSeq_;
    /**
     * <pre>
     *消息唯一标识，与对应的response一致。
     * </pre>
     *
     * <code>int32 msgSeq = 1;</code>
     * @return The msgSeq.
     */
    public int getMsgSeq() {
      return msgSeq_;
    }

    public static final int SVRTYPE_FIELD_NUMBER = 2;
    private int svrType_;
    /**
     * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
     * @return The enum numeric value on the wire for svrType.
     */
    public int getSvrTypeValue() {
      return svrType_;
    }
    /**
     * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
     * @return The svrType.
     */
    public com.seeu.framework.rpc.RpcMsg.ServerType getSvrType() {
      @SuppressWarnings("deprecation")
      com.seeu.framework.rpc.RpcMsg.ServerType result = com.seeu.framework.rpc.RpcMsg.ServerType.valueOf(svrType_);
      return result == null ? com.seeu.framework.rpc.RpcMsg.ServerType.UNRECOGNIZED : result;
    }

    public static final int SVRID_FIELD_NUMBER = 3;
    private int svrId_;
    /**
     * <code>int32 svrId = 3;</code>
     * @return The svrId.
     */
    public int getSvrId() {
      return svrId_;
    }

    public static final int METHOD_FIELD_NUMBER = 4;
    private volatile java.lang.Object method_;
    /**
     * <pre>
     *具体消息命令字定义，比如：user.login
     * </pre>
     *
     * <code>string method = 4;</code>
     * @return The method.
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *具体消息命令字定义，比如：user.login
     * </pre>
     *
     * <code>string method = 4;</code>
     * @return The bytes for method.
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEEDRESPONSE_FIELD_NUMBER = 5;
    private boolean needResponse_;
    /**
     * <pre>
     *是否需要等待响应
     * </pre>
     *
     * <code>bool needResponse = 5;</code>
     * @return The needResponse.
     */
    public boolean getNeedResponse() {
      return needResponse_;
    }

    public static final int CONTENT_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString content_;
    /**
     * <pre>
     *消息内容。
     * </pre>
     *
     * <code>bytes content = 6;</code>
     * @return The content.
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgSeq_ != 0) {
        output.writeInt32(1, msgSeq_);
      }
      if (svrType_ != com.seeu.framework.rpc.RpcMsg.ServerType.UNKNOWN.getNumber()) {
        output.writeEnum(2, svrType_);
      }
      if (svrId_ != 0) {
        output.writeInt32(3, svrId_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, method_);
      }
      if (needResponse_ != false) {
        output.writeBool(5, needResponse_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(6, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgSeq_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgSeq_);
      }
      if (svrType_ != com.seeu.framework.rpc.RpcMsg.ServerType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, svrType_);
      }
      if (svrId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, svrId_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, method_);
      }
      if (needResponse_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, needResponse_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.seeu.framework.rpc.RpcMsg.request)) {
        return super.equals(obj);
      }
      com.seeu.framework.rpc.RpcMsg.request other = (com.seeu.framework.rpc.RpcMsg.request) obj;

      if (getMsgSeq()
          != other.getMsgSeq()) return false;
      if (svrType_ != other.svrType_) return false;
      if (getSvrId()
          != other.getSvrId()) return false;
      if (!getMethod()
          .equals(other.getMethod())) return false;
      if (getNeedResponse()
          != other.getNeedResponse()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGSEQ_FIELD_NUMBER;
      hash = (53 * hash) + getMsgSeq();
      hash = (37 * hash) + SVRTYPE_FIELD_NUMBER;
      hash = (53 * hash) + svrType_;
      hash = (37 * hash) + SVRID_FIELD_NUMBER;
      hash = (53 * hash) + getSvrId();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      hash = (37 * hash) + NEEDRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNeedResponse());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.seeu.framework.rpc.RpcMsg.request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.seeu.framework.rpc.request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.seeu.framework.rpc.request)
        com.seeu.framework.rpc.RpcMsg.requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.seeu.framework.rpc.RpcMsg.request.class, com.seeu.framework.rpc.RpcMsg.request.Builder.class);
      }

      // Construct using com.seeu.framework.rpc.RpcMsg.request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgSeq_ = 0;

        svrType_ = 0;

        svrId_ = 0;

        method_ = "";

        needResponse_ = false;

        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_request_descriptor;
      }

      @java.lang.Override
      public com.seeu.framework.rpc.RpcMsg.request getDefaultInstanceForType() {
        return com.seeu.framework.rpc.RpcMsg.request.getDefaultInstance();
      }

      @java.lang.Override
      public com.seeu.framework.rpc.RpcMsg.request build() {
        com.seeu.framework.rpc.RpcMsg.request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.seeu.framework.rpc.RpcMsg.request buildPartial() {
        com.seeu.framework.rpc.RpcMsg.request result = new com.seeu.framework.rpc.RpcMsg.request(this);
        result.msgSeq_ = msgSeq_;
        result.svrType_ = svrType_;
        result.svrId_ = svrId_;
        result.method_ = method_;
        result.needResponse_ = needResponse_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.seeu.framework.rpc.RpcMsg.request) {
          return mergeFrom((com.seeu.framework.rpc.RpcMsg.request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.seeu.framework.rpc.RpcMsg.request other) {
        if (other == com.seeu.framework.rpc.RpcMsg.request.getDefaultInstance()) return this;
        if (other.getMsgSeq() != 0) {
          setMsgSeq(other.getMsgSeq());
        }
        if (other.svrType_ != 0) {
          setSvrTypeValue(other.getSvrTypeValue());
        }
        if (other.getSvrId() != 0) {
          setSvrId(other.getSvrId());
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        if (other.getNeedResponse() != false) {
          setNeedResponse(other.getNeedResponse());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.seeu.framework.rpc.RpcMsg.request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.seeu.framework.rpc.RpcMsg.request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgSeq_ ;
      /**
       * <pre>
       *消息唯一标识，与对应的response一致。
       * </pre>
       *
       * <code>int32 msgSeq = 1;</code>
       * @return The msgSeq.
       */
      public int getMsgSeq() {
        return msgSeq_;
      }
      /**
       * <pre>
       *消息唯一标识，与对应的response一致。
       * </pre>
       *
       * <code>int32 msgSeq = 1;</code>
       * @param value The msgSeq to set.
       * @return This builder for chaining.
       */
      public Builder setMsgSeq(int value) {
        
        msgSeq_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息唯一标识，与对应的response一致。
       * </pre>
       *
       * <code>int32 msgSeq = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgSeq() {
        
        msgSeq_ = 0;
        onChanged();
        return this;
      }

      private int svrType_ = 0;
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
       * @return The enum numeric value on the wire for svrType.
       */
      public int getSvrTypeValue() {
        return svrType_;
      }
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
       * @param value The enum numeric value on the wire for svrType to set.
       * @return This builder for chaining.
       */
      public Builder setSvrTypeValue(int value) {
        svrType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
       * @return The svrType.
       */
      public com.seeu.framework.rpc.RpcMsg.ServerType getSvrType() {
        @SuppressWarnings("deprecation")
        com.seeu.framework.rpc.RpcMsg.ServerType result = com.seeu.framework.rpc.RpcMsg.ServerType.valueOf(svrType_);
        return result == null ? com.seeu.framework.rpc.RpcMsg.ServerType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
       * @param value The svrType to set.
       * @return This builder for chaining.
       */
      public Builder setSvrType(com.seeu.framework.rpc.RpcMsg.ServerType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        svrType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSvrType() {
        
        svrType_ = 0;
        onChanged();
        return this;
      }

      private int svrId_ ;
      /**
       * <code>int32 svrId = 3;</code>
       * @return The svrId.
       */
      public int getSvrId() {
        return svrId_;
      }
      /**
       * <code>int32 svrId = 3;</code>
       * @param value The svrId to set.
       * @return This builder for chaining.
       */
      public Builder setSvrId(int value) {
        
        svrId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 svrId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSvrId() {
        
        svrId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login
       * </pre>
       *
       * <code>string method = 4;</code>
       * @return The method.
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login
       * </pre>
       *
       * <code>string method = 4;</code>
       * @return The bytes for method.
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login
       * </pre>
       *
       * <code>string method = 4;</code>
       * @param value The method to set.
       * @return This builder for chaining.
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login
       * </pre>
       *
       * <code>string method = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login
       * </pre>
       *
       * <code>string method = 4;</code>
       * @param value The bytes for method to set.
       * @return This builder for chaining.
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        method_ = value;
        onChanged();
        return this;
      }

      private boolean needResponse_ ;
      /**
       * <pre>
       *是否需要等待响应
       * </pre>
       *
       * <code>bool needResponse = 5;</code>
       * @return The needResponse.
       */
      public boolean getNeedResponse() {
        return needResponse_;
      }
      /**
       * <pre>
       *是否需要等待响应
       * </pre>
       *
       * <code>bool needResponse = 5;</code>
       * @param value The needResponse to set.
       * @return This builder for chaining.
       */
      public Builder setNeedResponse(boolean value) {
        
        needResponse_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否需要等待响应
       * </pre>
       *
       * <code>bool needResponse = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearNeedResponse() {
        
        needResponse_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *消息内容。
       * </pre>
       *
       * <code>bytes content = 6;</code>
       * @return The content.
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <pre>
       *消息内容。
       * </pre>
       *
       * <code>bytes content = 6;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容。
       * </pre>
       *
       * <code>bytes content = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.seeu.framework.rpc.request)
    }

    // @@protoc_insertion_point(class_scope:com.seeu.framework.rpc.request)
    private static final com.seeu.framework.rpc.RpcMsg.request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.seeu.framework.rpc.RpcMsg.request();
    }

    public static com.seeu.framework.rpc.RpcMsg.request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<request>
        PARSER = new com.google.protobuf.AbstractParser<request>() {
      @java.lang.Override
      public request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.seeu.framework.rpc.RpcMsg.request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface responseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.seeu.framework.rpc.response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息唯一标识，返回时与对应的request一致。
     * </pre>
     *
     * <code>int32 msgSeq = 1;</code>
     * @return The msgSeq.
     */
    int getMsgSeq();

    /**
     * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
     * @return The enum numeric value on the wire for svrType.
     */
    int getSvrTypeValue();
    /**
     * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
     * @return The svrType.
     */
    com.seeu.framework.rpc.RpcMsg.ServerType getSvrType();

    /**
     * <code>int32 svrId = 3;</code>
     * @return The svrId.
     */
    int getSvrId();

    /**
     * <pre>
     *具体消息命令字定义，比如：user.login      
     * </pre>
     *
     * <code>string method = 4;</code>
     * @return The method.
     */
    java.lang.String getMethod();
    /**
     * <pre>
     *具体消息命令字定义，比如：user.login      
     * </pre>
     *
     * <code>string method = 4;</code>
     * @return The bytes for method.
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <pre>
     *消息内容。
     * </pre>
     *
     * <code>bytes content = 5;</code>
     * @return The content.
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code com.seeu.framework.rpc.response}
   */
  public  static final class response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.seeu.framework.rpc.response)
      responseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use response.newBuilder() to construct.
    private response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private response() {
      svrType_ = 0;
      method_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgSeq_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              svrType_ = rawValue;
              break;
            }
            case 24: {

              svrId_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            case 42: {

              content_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seeu.framework.rpc.RpcMsg.response.class, com.seeu.framework.rpc.RpcMsg.response.Builder.class);
    }

    public static final int MSGSEQ_FIELD_NUMBER = 1;
    private int msgSeq_;
    /**
     * <pre>
     *消息唯一标识，返回时与对应的request一致。
     * </pre>
     *
     * <code>int32 msgSeq = 1;</code>
     * @return The msgSeq.
     */
    public int getMsgSeq() {
      return msgSeq_;
    }

    public static final int SVRTYPE_FIELD_NUMBER = 2;
    private int svrType_;
    /**
     * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
     * @return The enum numeric value on the wire for svrType.
     */
    public int getSvrTypeValue() {
      return svrType_;
    }
    /**
     * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
     * @return The svrType.
     */
    public com.seeu.framework.rpc.RpcMsg.ServerType getSvrType() {
      @SuppressWarnings("deprecation")
      com.seeu.framework.rpc.RpcMsg.ServerType result = com.seeu.framework.rpc.RpcMsg.ServerType.valueOf(svrType_);
      return result == null ? com.seeu.framework.rpc.RpcMsg.ServerType.UNRECOGNIZED : result;
    }

    public static final int SVRID_FIELD_NUMBER = 3;
    private int svrId_;
    /**
     * <code>int32 svrId = 3;</code>
     * @return The svrId.
     */
    public int getSvrId() {
      return svrId_;
    }

    public static final int METHOD_FIELD_NUMBER = 4;
    private volatile java.lang.Object method_;
    /**
     * <pre>
     *具体消息命令字定义，比如：user.login      
     * </pre>
     *
     * <code>string method = 4;</code>
     * @return The method.
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *具体消息命令字定义，比如：user.login      
     * </pre>
     *
     * <code>string method = 4;</code>
     * @return The bytes for method.
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString content_;
    /**
     * <pre>
     *消息内容。
     * </pre>
     *
     * <code>bytes content = 5;</code>
     * @return The content.
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgSeq_ != 0) {
        output.writeInt32(1, msgSeq_);
      }
      if (svrType_ != com.seeu.framework.rpc.RpcMsg.ServerType.UNKNOWN.getNumber()) {
        output.writeEnum(2, svrType_);
      }
      if (svrId_ != 0) {
        output.writeInt32(3, svrId_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, method_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(5, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgSeq_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgSeq_);
      }
      if (svrType_ != com.seeu.framework.rpc.RpcMsg.ServerType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, svrType_);
      }
      if (svrId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, svrId_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, method_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.seeu.framework.rpc.RpcMsg.response)) {
        return super.equals(obj);
      }
      com.seeu.framework.rpc.RpcMsg.response other = (com.seeu.framework.rpc.RpcMsg.response) obj;

      if (getMsgSeq()
          != other.getMsgSeq()) return false;
      if (svrType_ != other.svrType_) return false;
      if (getSvrId()
          != other.getSvrId()) return false;
      if (!getMethod()
          .equals(other.getMethod())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGSEQ_FIELD_NUMBER;
      hash = (53 * hash) + getMsgSeq();
      hash = (37 * hash) + SVRTYPE_FIELD_NUMBER;
      hash = (53 * hash) + svrType_;
      hash = (37 * hash) + SVRID_FIELD_NUMBER;
      hash = (53 * hash) + getSvrId();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.seeu.framework.rpc.RpcMsg.response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.seeu.framework.rpc.response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.seeu.framework.rpc.response)
        com.seeu.framework.rpc.RpcMsg.responseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.seeu.framework.rpc.RpcMsg.response.class, com.seeu.framework.rpc.RpcMsg.response.Builder.class);
      }

      // Construct using com.seeu.framework.rpc.RpcMsg.response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgSeq_ = 0;

        svrType_ = 0;

        svrId_ = 0;

        method_ = "";

        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_response_descriptor;
      }

      @java.lang.Override
      public com.seeu.framework.rpc.RpcMsg.response getDefaultInstanceForType() {
        return com.seeu.framework.rpc.RpcMsg.response.getDefaultInstance();
      }

      @java.lang.Override
      public com.seeu.framework.rpc.RpcMsg.response build() {
        com.seeu.framework.rpc.RpcMsg.response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.seeu.framework.rpc.RpcMsg.response buildPartial() {
        com.seeu.framework.rpc.RpcMsg.response result = new com.seeu.framework.rpc.RpcMsg.response(this);
        result.msgSeq_ = msgSeq_;
        result.svrType_ = svrType_;
        result.svrId_ = svrId_;
        result.method_ = method_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.seeu.framework.rpc.RpcMsg.response) {
          return mergeFrom((com.seeu.framework.rpc.RpcMsg.response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.seeu.framework.rpc.RpcMsg.response other) {
        if (other == com.seeu.framework.rpc.RpcMsg.response.getDefaultInstance()) return this;
        if (other.getMsgSeq() != 0) {
          setMsgSeq(other.getMsgSeq());
        }
        if (other.svrType_ != 0) {
          setSvrTypeValue(other.getSvrTypeValue());
        }
        if (other.getSvrId() != 0) {
          setSvrId(other.getSvrId());
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.seeu.framework.rpc.RpcMsg.response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.seeu.framework.rpc.RpcMsg.response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgSeq_ ;
      /**
       * <pre>
       *消息唯一标识，返回时与对应的request一致。
       * </pre>
       *
       * <code>int32 msgSeq = 1;</code>
       * @return The msgSeq.
       */
      public int getMsgSeq() {
        return msgSeq_;
      }
      /**
       * <pre>
       *消息唯一标识，返回时与对应的request一致。
       * </pre>
       *
       * <code>int32 msgSeq = 1;</code>
       * @param value The msgSeq to set.
       * @return This builder for chaining.
       */
      public Builder setMsgSeq(int value) {
        
        msgSeq_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息唯一标识，返回时与对应的request一致。
       * </pre>
       *
       * <code>int32 msgSeq = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgSeq() {
        
        msgSeq_ = 0;
        onChanged();
        return this;
      }

      private int svrType_ = 0;
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
       * @return The enum numeric value on the wire for svrType.
       */
      public int getSvrTypeValue() {
        return svrType_;
      }
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
       * @param value The enum numeric value on the wire for svrType to set.
       * @return This builder for chaining.
       */
      public Builder setSvrTypeValue(int value) {
        svrType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
       * @return The svrType.
       */
      public com.seeu.framework.rpc.RpcMsg.ServerType getSvrType() {
        @SuppressWarnings("deprecation")
        com.seeu.framework.rpc.RpcMsg.ServerType result = com.seeu.framework.rpc.RpcMsg.ServerType.valueOf(svrType_);
        return result == null ? com.seeu.framework.rpc.RpcMsg.ServerType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
       * @param value The svrType to set.
       * @return This builder for chaining.
       */
      public Builder setSvrType(com.seeu.framework.rpc.RpcMsg.ServerType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        svrType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.seeu.framework.rpc.ServerType svrType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSvrType() {
        
        svrType_ = 0;
        onChanged();
        return this;
      }

      private int svrId_ ;
      /**
       * <code>int32 svrId = 3;</code>
       * @return The svrId.
       */
      public int getSvrId() {
        return svrId_;
      }
      /**
       * <code>int32 svrId = 3;</code>
       * @param value The svrId to set.
       * @return This builder for chaining.
       */
      public Builder setSvrId(int value) {
        
        svrId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 svrId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSvrId() {
        
        svrId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login      
       * </pre>
       *
       * <code>string method = 4;</code>
       * @return The method.
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login      
       * </pre>
       *
       * <code>string method = 4;</code>
       * @return The bytes for method.
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login      
       * </pre>
       *
       * <code>string method = 4;</code>
       * @param value The method to set.
       * @return This builder for chaining.
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login      
       * </pre>
       *
       * <code>string method = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login      
       * </pre>
       *
       * <code>string method = 4;</code>
       * @param value The bytes for method to set.
       * @return This builder for chaining.
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        method_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *消息内容。
       * </pre>
       *
       * <code>bytes content = 5;</code>
       * @return The content.
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <pre>
       *消息内容。
       * </pre>
       *
       * <code>bytes content = 5;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容。
       * </pre>
       *
       * <code>bytes content = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.seeu.framework.rpc.response)
    }

    // @@protoc_insertion_point(class_scope:com.seeu.framework.rpc.response)
    private static final com.seeu.framework.rpc.RpcMsg.response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.seeu.framework.rpc.RpcMsg.response();
    }

    public static com.seeu.framework.rpc.RpcMsg.response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<response>
        PARSER = new com.google.protobuf.AbstractParser<response>() {
      @java.lang.Override
      public response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.seeu.framework.rpc.RpcMsg.response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seeu_framework_rpc_request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seeu_framework_rpc_request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seeu_framework_rpc_response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seeu_framework_rpc_response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014rpcMsg.proto\022\026com.seeu.framework.rpc\"\224" +
      "\001\n\007request\022\016\n\006msgSeq\030\001 \001(\005\0223\n\007svrType\030\002 " +
      "\001(\0162\".com.seeu.framework.rpc.ServerType\022" +
      "\r\n\005svrId\030\003 \001(\005\022\016\n\006method\030\004 \001(\t\022\024\n\014needRe" +
      "sponse\030\005 \001(\010\022\017\n\007content\030\006 \001(\014\"\177\n\010respons" +
      "e\022\016\n\006msgSeq\030\001 \001(\005\0223\n\007svrType\030\002 \001(\0162\".com" +
      ".seeu.framework.rpc.ServerType\022\r\n\005svrId\030" +
      "\003 \001(\005\022\016\n\006method\030\004 \001(\t\022\017\n\007content\030\005 \001(\014*3" +
      "\n\nServerType\022\013\n\007UNKNOWN\020\000\022\014\n\010DISCOVER\020\001\022" +
      "\n\n\006ACCESS\020\002B \n\026com.seeu.framework.rpcB\006R" +
      "pcMsgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_seeu_framework_rpc_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_seeu_framework_rpc_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seeu_framework_rpc_request_descriptor,
        new java.lang.String[] { "MsgSeq", "SvrType", "SvrId", "Method", "NeedResponse", "Content", });
    internal_static_com_seeu_framework_rpc_response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_seeu_framework_rpc_response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seeu_framework_rpc_response_descriptor,
        new java.lang.String[] { "MsgSeq", "SvrType", "SvrId", "Method", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
