// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcMsg.proto

package com.seeu.framework.rpc;

public final class RpcMsg {
  private RpcMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.seeu.framework.rpc.request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息唯一标识，与对应的response一致。
     * </pre>
     *
     * <code>int32 msgSeq = 1;</code>
     * @return The msgSeq.
     */
    int getMsgSeq();

    /**
     * <pre>
     *具体消息命令字定义，比如：user.login
     * </pre>
     *
     * <code>string method = 2;</code>
     * @return The method.
     */
    java.lang.String getMethod();
    /**
     * <pre>
     *具体消息命令字定义，比如：user.login
     * </pre>
     *
     * <code>string method = 2;</code>
     * @return The bytes for method.
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <pre>
     *是否需要等待响应
     * </pre>
     *
     * <code>bool needResponse = 3;</code>
     * @return The needResponse.
     */
    boolean getNeedResponse();

    /**
     * <pre>
     *消息内容。
     * </pre>
     *
     * <code>bytes content = 4;</code>
     * @return The content.
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code com.seeu.framework.rpc.request}
   */
  public  static final class request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.seeu.framework.rpc.request)
      requestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use request.newBuilder() to construct.
    private request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private request() {
      method_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgSeq_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            case 24: {

              needResponse_ = input.readBool();
              break;
            }
            case 34: {

              content_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seeu.framework.rpc.RpcMsg.request.class, com.seeu.framework.rpc.RpcMsg.request.Builder.class);
    }

    public static final int MSGSEQ_FIELD_NUMBER = 1;
    private int msgSeq_;
    /**
     * <pre>
     *消息唯一标识，与对应的response一致。
     * </pre>
     *
     * <code>int32 msgSeq = 1;</code>
     * @return The msgSeq.
     */
    public int getMsgSeq() {
      return msgSeq_;
    }

    public static final int METHOD_FIELD_NUMBER = 2;
    private volatile java.lang.Object method_;
    /**
     * <pre>
     *具体消息命令字定义，比如：user.login
     * </pre>
     *
     * <code>string method = 2;</code>
     * @return The method.
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *具体消息命令字定义，比如：user.login
     * </pre>
     *
     * <code>string method = 2;</code>
     * @return The bytes for method.
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEEDRESPONSE_FIELD_NUMBER = 3;
    private boolean needResponse_;
    /**
     * <pre>
     *是否需要等待响应
     * </pre>
     *
     * <code>bool needResponse = 3;</code>
     * @return The needResponse.
     */
    public boolean getNeedResponse() {
      return needResponse_;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString content_;
    /**
     * <pre>
     *消息内容。
     * </pre>
     *
     * <code>bytes content = 4;</code>
     * @return The content.
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgSeq_ != 0) {
        output.writeInt32(1, msgSeq_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, method_);
      }
      if (needResponse_ != false) {
        output.writeBool(3, needResponse_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(4, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgSeq_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgSeq_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, method_);
      }
      if (needResponse_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, needResponse_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.seeu.framework.rpc.RpcMsg.request)) {
        return super.equals(obj);
      }
      com.seeu.framework.rpc.RpcMsg.request other = (com.seeu.framework.rpc.RpcMsg.request) obj;

      if (getMsgSeq()
          != other.getMsgSeq()) return false;
      if (!getMethod()
          .equals(other.getMethod())) return false;
      if (getNeedResponse()
          != other.getNeedResponse()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGSEQ_FIELD_NUMBER;
      hash = (53 * hash) + getMsgSeq();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      hash = (37 * hash) + NEEDRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNeedResponse());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeu.framework.rpc.RpcMsg.request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.seeu.framework.rpc.RpcMsg.request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.seeu.framework.rpc.request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.seeu.framework.rpc.request)
        com.seeu.framework.rpc.RpcMsg.requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.seeu.framework.rpc.RpcMsg.request.class, com.seeu.framework.rpc.RpcMsg.request.Builder.class);
      }

      // Construct using com.seeu.framework.rpc.RpcMsg.request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgSeq_ = 0;

        method_ = "";

        needResponse_ = false;

        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_request_descriptor;
      }

      @java.lang.Override
      public com.seeu.framework.rpc.RpcMsg.request getDefaultInstanceForType() {
        return com.seeu.framework.rpc.RpcMsg.request.getDefaultInstance();
      }

      @java.lang.Override
      public com.seeu.framework.rpc.RpcMsg.request build() {
        com.seeu.framework.rpc.RpcMsg.request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.seeu.framework.rpc.RpcMsg.request buildPartial() {
        com.seeu.framework.rpc.RpcMsg.request result = new com.seeu.framework.rpc.RpcMsg.request(this);
        result.msgSeq_ = msgSeq_;
        result.method_ = method_;
        result.needResponse_ = needResponse_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.seeu.framework.rpc.RpcMsg.request) {
          return mergeFrom((com.seeu.framework.rpc.RpcMsg.request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.seeu.framework.rpc.RpcMsg.request other) {
        if (other == com.seeu.framework.rpc.RpcMsg.request.getDefaultInstance()) return this;
        if (other.getMsgSeq() != 0) {
          setMsgSeq(other.getMsgSeq());
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        if (other.getNeedResponse() != false) {
          setNeedResponse(other.getNeedResponse());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.seeu.framework.rpc.RpcMsg.request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.seeu.framework.rpc.RpcMsg.request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgSeq_ ;
      /**
       * <pre>
       *消息唯一标识，与对应的response一致。
       * </pre>
       *
       * <code>int32 msgSeq = 1;</code>
       * @return The msgSeq.
       */
      public int getMsgSeq() {
        return msgSeq_;
      }
      /**
       * <pre>
       *消息唯一标识，与对应的response一致。
       * </pre>
       *
       * <code>int32 msgSeq = 1;</code>
       * @param value The msgSeq to set.
       * @return This builder for chaining.
       */
      public Builder setMsgSeq(int value) {
        
        msgSeq_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息唯一标识，与对应的response一致。
       * </pre>
       *
       * <code>int32 msgSeq = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgSeq() {
        
        msgSeq_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login
       * </pre>
       *
       * <code>string method = 2;</code>
       * @return The method.
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login
       * </pre>
       *
       * <code>string method = 2;</code>
       * @return The bytes for method.
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login
       * </pre>
       *
       * <code>string method = 2;</code>
       * @param value The method to set.
       * @return This builder for chaining.
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login
       * </pre>
       *
       * <code>string method = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login
       * </pre>
       *
       * <code>string method = 2;</code>
       * @param value The bytes for method to set.
       * @return This builder for chaining.
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        method_ = value;
        onChanged();
        return this;
      }

      private boolean needResponse_ ;
      /**
       * <pre>
       *是否需要等待响应
       * </pre>
       *
       * <code>bool needResponse = 3;</code>
       * @return The needResponse.
       */
      public boolean getNeedResponse() {
        return needResponse_;
      }
      /**
       * <pre>
       *是否需要等待响应
       * </pre>
       *
       * <code>bool needResponse = 3;</code>
       * @param value The needResponse to set.
       * @return This builder for chaining.
       */
      public Builder setNeedResponse(boolean value) {
        
        needResponse_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否需要等待响应
       * </pre>
       *
       * <code>bool needResponse = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNeedResponse() {
        
        needResponse_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *消息内容。
       * </pre>
       *
       * <code>bytes content = 4;</code>
       * @return The content.
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <pre>
       *消息内容。
       * </pre>
       *
       * <code>bytes content = 4;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容。
       * </pre>
       *
       * <code>bytes content = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.seeu.framework.rpc.request)
    }

    // @@protoc_insertion_point(class_scope:com.seeu.framework.rpc.request)
    private static final com.seeu.framework.rpc.RpcMsg.request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.seeu.framework.rpc.RpcMsg.request();
    }

    public static com.seeu.framework.rpc.RpcMsg.request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<request>
        PARSER = new com.google.protobuf.AbstractParser<request>() {
      @java.lang.Override
      public request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.seeu.framework.rpc.RpcMsg.request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface responseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.seeu.framework.rpc.response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息唯一标识，返回时与对应的request一致。
     * </pre>
     *
     * <code>int32 msgSeq = 1;</code>
     * @return The msgSeq.
     */
    int getMsgSeq();

    /**
     * <code>string method = 2;</code>
     * @return The method.
     */
    java.lang.String getMethod();
    /**
     * <code>string method = 2;</code>
     * @return The bytes for method.
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <pre>
     *具体消息命令字定义，比如：user.login
     * </pre>
     *
     * <code>int32 code = 3;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <pre>
     *消息内容。
     * </pre>
     *
     * <code>bytes content = 4;</code>
     * @return The content.
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code com.seeu.framework.rpc.response}
   */
  public  static final class response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.seeu.framework.rpc.response)
      responseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use response.newBuilder() to construct.
    private response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private response() {
      method_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgSeq_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            case 24: {

              code_ = input.readInt32();
              break;
            }
            case 34: {

              content_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seeu.framework.rpc.RpcMsg.response.class, com.seeu.framework.rpc.RpcMsg.response.Builder.class);
    }

    public static final int MSGSEQ_FIELD_NUMBER = 1;
    private int msgSeq_;
    /**
     * <pre>
     *消息唯一标识，返回时与对应的request一致。
     * </pre>
     *
     * <code>int32 msgSeq = 1;</code>
     * @return The msgSeq.
     */
    public int getMsgSeq() {
      return msgSeq_;
    }

    public static final int METHOD_FIELD_NUMBER = 2;
    private volatile java.lang.Object method_;
    /**
     * <code>string method = 2;</code>
     * @return The method.
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <code>string method = 2;</code>
     * @return The bytes for method.
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 3;
    private int code_;
    /**
     * <pre>
     *具体消息命令字定义，比如：user.login
     * </pre>
     *
     * <code>int32 code = 3;</code>
     * @return The code.
     */
    public int getCode() {
      return code_;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString content_;
    /**
     * <pre>
     *消息内容。
     * </pre>
     *
     * <code>bytes content = 4;</code>
     * @return The content.
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgSeq_ != 0) {
        output.writeInt32(1, msgSeq_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, method_);
      }
      if (code_ != 0) {
        output.writeInt32(3, code_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(4, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgSeq_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgSeq_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, method_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, code_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.seeu.framework.rpc.RpcMsg.response)) {
        return super.equals(obj);
      }
      com.seeu.framework.rpc.RpcMsg.response other = (com.seeu.framework.rpc.RpcMsg.response) obj;

      if (getMsgSeq()
          != other.getMsgSeq()) return false;
      if (!getMethod()
          .equals(other.getMethod())) return false;
      if (getCode()
          != other.getCode()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGSEQ_FIELD_NUMBER;
      hash = (53 * hash) + getMsgSeq();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeu.framework.rpc.RpcMsg.response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.seeu.framework.rpc.RpcMsg.response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.seeu.framework.rpc.response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.seeu.framework.rpc.response)
        com.seeu.framework.rpc.RpcMsg.responseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.seeu.framework.rpc.RpcMsg.response.class, com.seeu.framework.rpc.RpcMsg.response.Builder.class);
      }

      // Construct using com.seeu.framework.rpc.RpcMsg.response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgSeq_ = 0;

        method_ = "";

        code_ = 0;

        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.seeu.framework.rpc.RpcMsg.internal_static_com_seeu_framework_rpc_response_descriptor;
      }

      @java.lang.Override
      public com.seeu.framework.rpc.RpcMsg.response getDefaultInstanceForType() {
        return com.seeu.framework.rpc.RpcMsg.response.getDefaultInstance();
      }

      @java.lang.Override
      public com.seeu.framework.rpc.RpcMsg.response build() {
        com.seeu.framework.rpc.RpcMsg.response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.seeu.framework.rpc.RpcMsg.response buildPartial() {
        com.seeu.framework.rpc.RpcMsg.response result = new com.seeu.framework.rpc.RpcMsg.response(this);
        result.msgSeq_ = msgSeq_;
        result.method_ = method_;
        result.code_ = code_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.seeu.framework.rpc.RpcMsg.response) {
          return mergeFrom((com.seeu.framework.rpc.RpcMsg.response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.seeu.framework.rpc.RpcMsg.response other) {
        if (other == com.seeu.framework.rpc.RpcMsg.response.getDefaultInstance()) return this;
        if (other.getMsgSeq() != 0) {
          setMsgSeq(other.getMsgSeq());
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.seeu.framework.rpc.RpcMsg.response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.seeu.framework.rpc.RpcMsg.response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgSeq_ ;
      /**
       * <pre>
       *消息唯一标识，返回时与对应的request一致。
       * </pre>
       *
       * <code>int32 msgSeq = 1;</code>
       * @return The msgSeq.
       */
      public int getMsgSeq() {
        return msgSeq_;
      }
      /**
       * <pre>
       *消息唯一标识，返回时与对应的request一致。
       * </pre>
       *
       * <code>int32 msgSeq = 1;</code>
       * @param value The msgSeq to set.
       * @return This builder for chaining.
       */
      public Builder setMsgSeq(int value) {
        
        msgSeq_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息唯一标识，返回时与对应的request一致。
       * </pre>
       *
       * <code>int32 msgSeq = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgSeq() {
        
        msgSeq_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <code>string method = 2;</code>
       * @return The method.
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string method = 2;</code>
       * @return The bytes for method.
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method = 2;</code>
       * @param value The method to set.
       * @return This builder for chaining.
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string method = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>string method = 2;</code>
       * @param value The bytes for method to set.
       * @return This builder for chaining.
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        method_ = value;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login
       * </pre>
       *
       * <code>int32 code = 3;</code>
       * @return The code.
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login
       * </pre>
       *
       * <code>int32 code = 3;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *具体消息命令字定义，比如：user.login
       * </pre>
       *
       * <code>int32 code = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *消息内容。
       * </pre>
       *
       * <code>bytes content = 4;</code>
       * @return The content.
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <pre>
       *消息内容。
       * </pre>
       *
       * <code>bytes content = 4;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容。
       * </pre>
       *
       * <code>bytes content = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.seeu.framework.rpc.response)
    }

    // @@protoc_insertion_point(class_scope:com.seeu.framework.rpc.response)
    private static final com.seeu.framework.rpc.RpcMsg.response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.seeu.framework.rpc.RpcMsg.response();
    }

    public static com.seeu.framework.rpc.RpcMsg.response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<response>
        PARSER = new com.google.protobuf.AbstractParser<response>() {
      @java.lang.Override
      public response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.seeu.framework.rpc.RpcMsg.response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seeu_framework_rpc_request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seeu_framework_rpc_request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seeu_framework_rpc_response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seeu_framework_rpc_response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014rpcMsg.proto\022\026com.seeu.framework.rpc\"P" +
      "\n\007request\022\016\n\006msgSeq\030\001 \001(\005\022\016\n\006method\030\002 \001(" +
      "\t\022\024\n\014needResponse\030\003 \001(\010\022\017\n\007content\030\004 \001(\014" +
      "\"I\n\010response\022\016\n\006msgSeq\030\001 \001(\005\022\016\n\006method\030\002" +
      " \001(\t\022\014\n\004code\030\003 \001(\005\022\017\n\007content\030\004 \001(\014B \n\026c" +
      "om.seeu.framework.rpcB\006RpcMsgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_seeu_framework_rpc_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_seeu_framework_rpc_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seeu_framework_rpc_request_descriptor,
        new java.lang.String[] { "MsgSeq", "Method", "NeedResponse", "Content", });
    internal_static_com_seeu_framework_rpc_response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_seeu_framework_rpc_response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seeu_framework_rpc_response_descriptor,
        new java.lang.String[] { "MsgSeq", "Method", "Code", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
